
[[Snippets]]
  Description = "netdiscover, permet de découvrir les adresses IP sur un reseau"
  Output = ""
  Tag = ["netdiscover"]
  command = "sudo netdiscover -i <notre-interface(eth0)> -r <ip(192.168.1.0)>"

[[Snippets]]
  Description = "nmap, sniffer les ports d'une ip"
  Output = ""
  Tag = ["nmap"]
  command = "nmap -sT <adresse-ip>/<cidr>"

[[Snippets]]
  Description = "nmap, avoir toutes les infos d'une adresse IP"
  Output = ""
  Tag = ["nmap"]
  command = "nmap -A <adresse-ip>"

[[Snippets]]
  Description = "nmap, permet de faire un scan discret -sS et de détecter la version des services -sV"
  Output = ""
  Tag = ["nmap"]
  command = "sudo nmap -sS -sV <adresse_ip>"

[[Snippets]]
  Description = "nmap, fait un scan classique (non discret)"
  Output = ""
  Tag = ["nmap"]
  command = "nmap -sT <IP(192.168.10.0)>/<CIDR>"

[[Snippets]]
  Description = "nmap, list les machines actives sur un réseau sans scanner leurs ports"
  Output = ""
  Tag = ["nmap"]
  command = "nmap -sn <IP(192.168.10.0)>/<CIDR>"

[[Snippets]]
  Description = "nmap, essaye de detecter l'OS"
  Output = ""
  Tag = ["nmap"]
  command = "sudo nmap -O <IP(192.168.10.0)>/<CIDR>"

[[Snippets]]
  Description = "nmap, scan avancé de l’IP cible en forçant le scan des ports, en cherchant les vulnérabilités connues, en identifiant l’OS et les services, et en bypassant la détection d’hôtes, ignore le ping (-Pn)"
  Output = ""
  Tag = ["nmap"]
  command = "nmap -A --script vuln,safe --script-args=unsafe=1 --top-ports <Port(1000)> -Pn <adresse-ip>"

[[Snippets]]
  Description = "nmap, permet d'identifier le(s) serveurs DHCP"
  Output = ""
  Tag = ["nmap"]
  command = "sudo nmap --script broadcast-dhcp-discover"

[[Snippets]]
  Description = "nbtscan, identifie les machines Windows sur un réseau"
  Output = ""
  Tag = ["nbtscan"]
  command = "nbtscan <IP(192.168.150.1)>/<CIDR>"

[[Snippets]]
  Description = "nmap, permet de scanner tous les services sur tout les ports"
  Output = ""
  Tag = ["nmap"]
  command = "nmap -A <IP(192.168.167.131)> -p-"

[[Snippets]]
  Description = "nmap, fait un scan UDP sur tout les ports"
  Output = ""
  Tag = ["nmap"]
  command = "sudo nmap -sU <adresse-ip> -p-"

[[Snippets]]
  Description = "enum4linux, permet de scanner un hote windows en profondeur (-a)"
  Output = ""
  Tag = ["enum4minux"]
  command = "enum4linux -a <adresse-ip>"

[[Snippets]]
  Description = "dirb, permet de découvrir tout les dossiers d'un site web"
  Output = ""
  Tag = ["dirb"]
  command = "dirb <http-ou-https>://<adresse-ip>"

[[Snippets]]
  Description = "enum4linux, permet d'enumerer les utilisateurs windows via SMB"
  Output = ""
  Tag = ["enum4linux"]
  command = "enum4linux -U <IP>"

[[Snippets]]
  Description = "responder, outil de man-in-the-middle (MITM) utilisé pour capturer des requêtes sur le réseau local (LAN), en particulier celles liées à des services tels que NetBIOS, LLMNR, NBT-NS, et MDNS. Il exploite les vulnérabilités de protocoles non sécurisés pour intercepter des informations sensibles comme des identifiants et mots de passe non chiffrés"
  Output = ""
  Tag = ["responder"]
  command = "sudo responder -I <interface(eth0)> <--lm(permet de downgrade)>"

[[Snippets]]
  Description = "crackmapexec, permet de récupérer les users en utilisant le service SMB sur une IP"
  Output = ""
  Tag = ["crackmapexec"]
  command = "crackmapexec smb <adresse-ip> --users"

[[Snippets]]
  Description = "crackmapexec, permet de récupérer les partages (repertoire partagee) en utilisant le service SMB sur une IP"
  Output = ""
  Tag = ["crackmapexec"]
  command = "crackmapexec smb <adresse-ip> --shares"

[[Snippets]]
  Description = "smbclient.py, permet d'avoir accès au(x) partage(s) sur une adresse IP ; ATTENTION il faut le mdp de l'utilisateur"
  Output = ""
  Tag = ["smbclient.py"]
  command = "python3 smbclient.py <nom-du-domaine(north.sevenkingdoms.local)>/<nom-utilisateur-sam-account-name>@<adresse-ip>"

[[Snippets]]
  Description = "smbmap, permet d'avoir accès au(x) partage(s) sur une adresse IP ; ATTENTION il faut le mdp de l'utilisateur"
  Output = ""
  Tag = ["smbmap"]
  command = "smbmap -u <nom-utilisateur> -p <mot-de-passe> -H <IP(192.168.86.61)>"

[[Snippets]]
  Description = "bloodhound, permet d'avoir une sortie zip d'un domaine pour bloodhound"
  Output = ""
  Tag = ["bloodhound"]
  command = "bloodhound-python -d <nom-du-domaine> --zip -c All -dc <nom-du-domain-controller> -ns <IP-du-domaine> -u '<user>' -p '<password>'"

[[Snippets]]
  Description = "proxychains4, permet de dump la base SAM"
  Output = ""
  Tag = ["proxychains4"]
  command = "proxychains4 -q secretsdump.py <domain>/<user>:toto@<IP>"

[[Snippets]]
  Description = "dig, permet de faire un transfert de zone DNS"
  Output = ""
  Tag = ["dig"]
  command = "dig -axfr <nom-de-domaine>@<nom-server>"

[[Snippets]]
  Description = "ldapsearch, permet d'identifier les informations de configuration de base du serveur LDAP (NETLOGON,SYSVOL,IPC$...)"
  Output = ""
  Tag = ["ldapsearch"]
  command = "ldapsearch -x -H ldap://<IP-du-domaine> -s base"

[[Snippets]]
  Description = "mitm6, intercept les communications (MITM) d'un domaine"
  Output = ""
  Tag = ["mitm6"]
  command = "sudo mitm6 -d <nom-du-domaine> -I <Interface(eth0)>"

[[Snippets]]
  Description = "ntlmrelay.py, permet de relayer une authentification NTLM capturée vers un autre service"
  Output = ""
  Tag = ["ntlmrelay.py"]
  command = "ntmlrelayx.py -tf <targets.txt> -smb2support -socks"

[[Snippets]]
  Description = "crackmapexec, permet de faire une attaque PathTheHash ; NTLMV2 est le hash du password du user"
  Output = ""
  Tag = ["crackmapexec"]
  command = "crackmapexec smb <IP> -u '<user>' -H <NTLMV2> --shares"

[[Snippets]]
  Description = "docker, permet de supprimer toutes les images"
  Output = ""
  Tag = ["docker"]
  command = "docker rmi $(docker images -a -q)"

[[Snippets]]
  Description = "docker, permet de supprimer tous les volumes"
  Output = ""
  Tag = ["docker"]
  command = "docker volume rm $(docker volume ls -q)"

[[Snippets]]
  Description = "docker, arreter tout les containers docker"
  Output = ""
  Tag = ["docker"]
  command = "docker stop $(docker ps -q)"

[[Snippets]]
  Description = "docker, permet de supprimer tout les containers docker"
  Output = ""
  Tag = ["docker"]
  command = "docker rm $(docker ps -aq)"

[[Snippets]]
  Description = "xfreerdp, permet de prendre la main en RDP"
  Output = ""
  Tag = ["xfreerdp"]
  command = "xfreerdp -u:<user> -p:<mdp> -v:<ip>"

[[Snippets]]
  Description = "docker, permet de supprimer toutes les ressources non utilisées"
  Output = ""
  Tag = ["docker"]
  command = "docker system prune -a <-f>"

[[Snippets]]
  Description = "xfreerdp, AVD2"
  Output = ""
  Tag = ["xfreerdp"]
  command = "xfreerdp -u:Administrateur -p:<mdp> -v:4.212.12.215"

[[Snippets]]
  Description = "xfreerdp, AVD1"
  Output = ""
  Tag = ["xfreerdp"]
  command = "xfreerdp -u:Administrateur -p:<mdp> -v:51.11.211.157"

[[Snippets]]
  Description = "xfreerdp, AVD3"
  Output = ""
  Tag = ["xfreerdp"]
  command = "xfreerdp -u:Administrateur -p:<mdp> -v:4.178.190.47"

[[Snippets]]
  Description = "xfreerdp, OgapConcept"
  Output = ""
  Tag = ["xfreerdp"]
  command = "xfreerdp -u:Administrateur -p:<mdp> -v:40.89.131.253"

[[Snippets]]
  Description = "find, chercher un fichier dans tout l'ordinateur"
  Output = ""
  Tag = ["find"]
  command = "sudo find / -type f -name \"<nom-du-fichier>\" 2>/dev/null"

[[Snippets]]
  Description = "find, chercher un dossier dans tout l'ordinateur"
  Output = ""
  Tag = ["find"]
  command = "sudo find / -type d -name \"<nom-du-dossier>\" 2>/dev/null"

[[Snippets]]
  Description = "find, chercher un fichier dans tout l'ordinateur, insensible à la casse (qui contient le mot)"
  Output = ""
  Tag = ["find"]
  command = "sudo find / -type f -iname \"*<nom-du-fichier>*\" 2>/dev/null"

[[Snippets]]
  Description = "find, chercher un dossier dans tout l'ordinateur, insensible à la casse (qui contient le mot)"
  Output = ""
  Tag = ["find"]
  command = "sudo find / -type d -iname \"*<nom-du-dossier>*\" 2>/dev/null"

[[Snippets]]
  Description = "xfreerdp, winerl - SRV-APP-WINERL"
  Output = ""
  Tag = ["xfreerdp"]
  command = "xfreerdp -u:supportproxit -p:<mdp> -v:4.178.153.109"

[[Snippets]]
  Description = "xfreerdp, winerl - AVD-WINERL"
  Output = ""
  Tag = ["xfreerdp"]
  command = "xfreerdp -u:supportproxit -p:<mdp> -v:4.211.105.162"

[[Snippets]]
  Description = "docker, ATTENTION !!! permet de nettoyer tout docker"
  Output = ""
  Tag = ["docker"]
  command = "docker system prune -a"

[[Snippets]]
  Description = "ffmpeg, concatener 2 audios"
  Output = ""
  Tag = ["ffmpeg"]
  command = "ffmpeg -i <premier-audio.wav> -i <second-audio.wav> -filter_complex \"[0:0][1:0]concat=n=2:v=0:a=1[out]\" -map \"[out]\" output.wav"

[[Snippets]]
  Description = "ssh, générer un paire de clé ssh (sur le client)"
  Output = ""
  Tag = ["ssh"]
  command = "ssh-keygen -t <ed25519 ou ecdsa ou rsa> -N \"<passphrase-si vide pas de passphrase>\" -f ~/.ssh/<key-name>"

[[Snippets]]
  Description = "ssh, permet de copier un clé ssh publique spécifique vers un serveur distant (depuis un client)"
  Output = ""
  Tag = ["ssh"]
  command = "ssh-copy-id -f -i <ssh-key.pub> <remote-user>@<remote-ip>"

[[Snippets]]
  Description = "ssh, se connecter en ssh à un hôte distant"
  Output = ""
  Tag = ["ssh"]
  command = "ssh <remote-user>@<remote-ip>"
